### ISSUE TITLE
Add instructions to each task

### ISSUE THREAD

**Issue by kimberly-bm** [jblashill/timecode-ui#2]
Hi, could you add these instructions in italicized text under the headers on each page? Thanks!

For Task 1: 
Set the timecode below to be 24 minutes, 17 seconds, and 2 frames into the video clip.

For Task 2:
This video clip is an hour long. Divide the content into 3 equal segments, 20 minutes each.

For Task 3:
The start of this video has a few black frames. Set the timecode to be the first non-black frame.

**Comment by jblashill** [comment]
Done!
